CREATE TABLE Acting (
    movieID INT,
    actorID INT
);
INSERT INTO Acting VALUES (1,1);
INSERT INTO Acting VALUES (2,2);
INSERT INTO Acting VALUES (3,3);
INSERT INTO Acting VALUES (4,4);
INSERT INTO Acting VALUES (5,5);
INSERT INTO Acting VALUES (6,6);
INSERT INTO Acting VALUES (7,7);
INSERT INTO Acting VALUES (8,8);
INSERT INTO Acting VALUES (9,9);
INSERT INTO Acting VALUES (10,10);
INSERT INTO Acting VALUES (11,11);
INSERT INTO Acting VALUES (12,12);
INSERT INTO Acting VALUES (13,13);
INSERT INTO Acting VALUES (14,14);
INSERT INTO Acting VALUES (15,15);
INSERT INTO Acting VALUES (16,16);
INSERT INTO Acting VALUES (17,17);
INSERT INTO Acting VALUES (18,18);
INSERT INTO Acting VALUES (19,19);
