CREATE TABLE Directing (
    movieID INT,
    directorID INT
);
INSERT INTO Directing VALUES (1,1);
INSERT INTO Directing VALUES (2,2);
INSERT INTO Directing VALUES (3,3);
INSERT INTO Directing VALUES (4,4);
INSERT INTO Directing VALUES (5,5);
INSERT INTO Directing VALUES (6,6);
INSERT INTO Directing VALUES (7,3);
INSERT INTO Directing VALUES (8,7);
INSERT INTO Directing VALUES (9,8);
INSERT INTO Directing VALUES (10,9);
INSERT INTO Directing VALUES (11,10);
INSERT INTO Directing VALUES (12,11);
INSERT INTO Directing VALUES (13,12);
INSERT INTO Directing VALUES (14,13);
INSERT INTO Directing VALUES (15,14);
INSERT INTO Directing VALUES (16,15);
INSERT INTO Directing VALUES (17,16);
INSERT INTO Directing VALUES (18,17);
INSERT INTO Directing VALUES (19,18);
